name: RainbowText
version: '${project.version}'
main: eu.sordiddev.rainbowtext.RainbowText
api-version: 1.18
authors: [ sord1d ]
description: Adds a gradient to your text
website: github.com/sord1d
permissions:
  rainbowtext.use:
commands:
  rtrs:
  rtgs:
  rtys:
  rtbs:
  rtr:
  rtg:
  rtb:
  rty:
  rt: